import { Report } from './db';

export const INITIAL_DEMO_REPORTS: Report[] = [
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1001',
    tracking_code: 'CFX-2026-0001',
    reporter_name: 'Marcus Vance',
    reporter_phone: '+1 (555) 234-8901',
    photo_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Deep road collapse near intersection. Vehicles bottoming out and swerving into oncoming traffic.',
    transcript: 'Huge pothole about eight inches deep right in the right lane on 4th Ave and Pine. It just popped a tire on a delivery van.',
    location: '4th Ave & Pine St, Downtown',
    category: 'Roads & Pavement',
    severity_score: 9,
    confidence_score: 0.94,
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 245,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    recommended_action: 'Emergency dispatch cold-patch asphalt crew and place traffic safety cones.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1002',
    tracking_code: 'CFX-2026-0002',
    reporter_name: 'Elena Rostova',
    reporter_phone: '+1 (555) 412-9980',
    photo_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Downed power wire hanging low over sidewalk and bike lane after storm wind.',
    transcript: 'Sparking wire hanging from the pole right above the sidewalk on Elm Street between 8th and 9th. Pedestrians are walking near it.',
    location: 'Elm St & 8th Ave, Midtown',
    category: 'Electrical & Power Grid',
    severity_score: 10,
    confidence_score: 0.98,
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 198,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    recommended_action: 'Critical safety alert: Notify power utility immediately and dispatch police to block sidewalk.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1003',
    tracking_code: 'CFX-2026-0003',
    reporter_name: 'David Chen',
    reporter_phone: '+1 (555) 872-3341',
    photo_url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Storm drain completely choked with tree debris and trash, street is flooding into crosswalk.',
    transcript: 'Water is backing up all over Market Street crosswalk because the storm grate is clogged with plastic bags and branches.',
    location: 'Market St & 5th Ave',
    category: 'Water & Stormwater Drainage',
    severity_score: 8,
    confidence_score: 0.91,
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 220,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    recommended_action: 'Deploy vacuum truck crew to clear catch basin grate and inspect downstream culvert.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1004',
    tracking_code: 'CFX-2026-0004',
    reporter_name: 'Aisha Jordan',
    reporter_phone: '+1 (555) 331-7722',
    photo_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Large pothole on 4th and Pine, cars are swerving.',
    transcript: 'Another car just hit the giant pothole at 4th and Pine downtown. Very dangerous.',
    location: '4th Ave & Pine St, Downtown',
    category: 'Roads & Pavement',
    severity_score: 9,
    confidence_score: 0.92,
    duplicate_of: 'f1a9b201-4c56-42d8-91e8-7801a23b1001', // Duplicate of CFX-2026-0001
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 210,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    recommended_action: 'Merged with existing primary report CFX-2026-0001.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1005',
    tracking_code: 'CFX-2026-0005',
    reporter_name: 'Sarah Jenkins',
    reporter_phone: '+1 (555) 762-1144',
    photo_url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Corner of 5th and Market drain is flooded with garbage.',
    transcript: 'Water rising near the curb at 5th and Market, storm drain completely backed up with leaves.',
    location: '5th Ave & Market St',
    category: 'Water & Stormwater Drainage',
    severity_score: 8,
    confidence_score: 0.89,
    duplicate_of: 'f1a9b201-4c56-42d8-91e8-7801a23b1003', // Duplicate of CFX-2026-0003
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 205,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    recommended_action: 'Merged with existing primary report CFX-2026-0003.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1006',
    tracking_code: 'CFX-2026-0006',
    reporter_name: 'Carlos Mendez',
    reporter_phone: '+1 (555) 609-8812',
    photo_url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Tree root heaved sidewalk slab up by 4 inches, trip hazard for seniors and wheelchairs.',
    transcript: 'Sidewalk is broken and raised up outside the elementary school on Maple Street. An elderly gentleman tripped earlier.',
    location: '340 Maple Street, Westside',
    category: 'Sidewalks & Pedestrian Access',
    severity_score: 6,
    confidence_score: 0.86,
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 230,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    recommended_action: 'Schedule sidewalk grinding crew and evaluate tree root barrier installation.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1007',
    tracking_code: 'CFX-2026-0007',
    reporter_name: 'Liam O’Connor',
    reporter_phone: '+1 (555) 901-4455',
    photo_url: null,
    video_url: null,
    text_description: 'Streetlight has been flickering and completely dark for 3 nights in a row.',
    transcript: 'The street lamp right in front of 712 Oak Street is completely out, makes the whole crosswalk pitch black at night.',
    location: '712 Oak Street',
    category: 'Street Lighting',
    severity_score: 4,
    confidence_score: 0.52, // Below 0.6 -> Flagged for human review!
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 180,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 15).toISOString(),
    recommended_action: 'Flagged for human review due to absence of photo evidence. Dispatch lighting technician.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1008',
    tracking_code: 'CFX-2026-0008',
    reporter_name: 'Brenda Washington',
    reporter_phone: '+1 (555) 345-6677',
    photo_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    text_description: 'Illegal dumping of old mattresses, drywall, and chemical paint cans in back alleyway.',
    transcript: 'Someone dumped construction debris and old mattresses blocking the alley behind 22nd Street.',
    location: 'Alleyway behind 22nd St & Cedar',
    category: 'Sanitation & Illegal Dumping',
    severity_score: 5,
    confidence_score: 0.88,
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 215,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    recommended_action: 'Dispatch bulk sanitation truck and inspect for hazardous paint solvents.',
    mock: false,
  },
  {
    id: 'f1a9b201-4c56-42d8-91e8-7801a23b1009',
    tracking_code: 'CFX-2026-0009',
    reporter_name: 'Hannah Abbott',
    reporter_phone: '+1 (555) 819-2041',
    photo_url: null,
    video_url: null,
    text_description: 'Faint gas or sewage odor near playground park entrance.',
    transcript: 'I smelled a strong sulfur or gas smell when walking dog past the city park bench.',
    location: 'Jefferson Park South Gate',
    category: 'Water & Sanitation',
    severity_score: 7,
    confidence_score: 0.45, // Below 0.6 -> Flagged for human review!
    duplicate_of: null,
    model_name: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    gpu_type: 'L40S',
    latency_ms: 195,
    status: 'reported',
    created_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    recommended_action: 'Flagged for human review (low confidence sensory report). Dispatch gas utility inspector.',
    mock: false,
  }
];
